call build.bat conf\bulgaria.props
call build.bat conf\greece.props
call build.bat conf\albania.props
call build.bat conf\makedonia.props
call build.bat conf\montenegro.props
call build.bat conf\slovenia.props
call build.bat conf\bih.props
::call build.bat conf\kosovo.props
call build.bat conf\croatia.props
call build.bat conf\serbia.props
call build.bat conf\romania.props
::call build.bat conf\italy.props
